name: nostra_pkg
description: This package published for training purpose only. Udah ah gitu aja. Pokoknya lebih dari 60 char hehehe.
version: 1.0.1

repository: https://github.com/tontonanrakyat/nostra_pkg
homepage: https://github.com/tontonanrakyat/nostra_pkg/blob/main/README.md

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
